spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider-admin
server:
  port: 11001

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
