spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-admin
server:
  port: 12000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/